### PR TITLE
Refactorings to complement large PR in LanguageServerProtocol

### PR DESCRIPTION
**Pull request by koliyo**
This should be updated to match whatever is decided in the main PR:
https://github.com/ChimeHQ/LanguageServerProtocol/pull/8

### CODE REVIEW

**Comment by mattmassicotte** [comment]
I think we can finally revisit this now!

**Comment by koliyo** [comment]
```
Building for debugging...
/Users/nils/Work/hylo-lsp/LanguageClient/Tests/LanguageClientTests/ServerTests.swift:46:3: error: global function 'XCTAssertEqual(_:_:_:file:line:)' requires that 'MockServer.ClientMessage' conform to 'Equatable'
                XCTAssertEqual(messages, [
                ^
Swift.Array:1:11: note: requirement from conditional conformance of '[MockServer.ClientMessage]' to 'Equatable'
extension Array : Equatable where Element : Equatable {
          ^
error: fatalError
```

Note sure what to do about this, if we should make ClientMessage Equatable or refactor test?

**Comment by mattmassicotte** [comment]
Now that `ClientRequest` takes captures closures, it is not longer possible to make an equality check. So, it won't be possible to make `MockServer.ClientMessage` conform to equatable. We'll have to refactor the test.

**Comment by mattmassicotte** [comment]
I think it will be a little annoying, but it should be possible to do a similar check by pulling out the non-closure data and comparing that.

**Comment by koliyo** [comment]
Ok, I will leave that to you if you (?) 😅 
Let me know if you need some updates from my side!

**Comment by mattmassicotte** [comment]
Yeah that makes sense. I'd actually like to look a little more closely at this PR too. Next week!

**Comment by mattmassicotte** [comment]
Also, Nils, I just wanted to thank you for all your work here. I'm amazed!

Since I don't have other ways to get in touch with you, I just wanted to make you aware that I have a Discord server set up specifically for work on these open source projects. Totally optional, but in case that's your kind of thing: https://discord.gg/esFpX6sErJ

**Comment by koliyo** [comment]
Well thank you! I'm glad I did not have to start from zero, and this was a great opportunity to get familiar with swift!

I'll join the discord. I probably won't be very active, but nice to be part of the community!

**Pull request merged**
